[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: blob:"

[[headers]]
  for = "/**/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/**/*.unityweb"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/**/*.wasm.br"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/**/*.data.br"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/**/*.js.br"
  [headers.values]
    Content-Type = "application/javascript"
